<a href="https://colab.research.google.com/github/Adeajakaye/DS.doyin/blob/master/myFirstColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np


In [3]:
data = np.array(2,3,4,5)

ValueError: ignored

In [4]:
data = np.array([2,3,4])

In [5]:
data

array([2, 3, 4])

In [6]:
type(data)

numpy.ndarray

In [9]:
data1 = np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
data1.shape

(2, 4)

In [12]:
data1.size

8

In [13]:
data

array([2, 3, 4])

In [14]:
#slicing through data

In [15]:
data[0]

2

In [16]:
data[1:2]

array([3])

In [17]:
data[:2]

array([2, 3])

In [18]:
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
data1[1,3]

8

In [22]:
data1.size

8

In [23]:
data1[1:3]

array([[5, 6, 7, 8]])

In [24]:
data1[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
data1[:1]

array([[1, 2, 3, 4]])

In [26]:
data1[:1,1:2]

array([[2]])

In [27]:
data1[1,2]

7

In [28]:
data1[-1,-3]

6

In [29]:
data1[0,:]

array([1, 2, 3, 4])

In [30]:
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
data1[1,2]

7

In [32]:
data1[1,:2]

array([5, 6])

In [33]:
data1[1,1:3]

array([6, 7])

In [34]:
#The "in" statement for np arrays


In [35]:
45 in data1

False

In [36]:
9 in data1

False

In [37]:
3 in data1

True

In [38]:
data_range = np.array(range(20))

In [39]:
data_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
data_range.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
data_range.shape

(20,)

In [42]:
data_range.size

20